### ISSUE TITLE
Duvida dos requisitos

### ISSUE THREAD

**Issue by coabr** [reprograma/On5-projeto-final#2]
Olá! Eu tava lendo o README e notei que diz "Sua página pessoal deverá ter o mesmo cabeçalho 'header' ", mas não seria a barra do 'nav'?

**Comment by jackelinerozenolopes** [comment]
Oie. Por favor, pode me ajudar numa questão?
Não entendi bem como faço para pôr o link da página inicial com todas as mulheres maravilhosas no meu botão VER MAIS MULHERES. Onde devo por esse index com todas as mulheres???
